### ISSUE TITLE
OpenRTB integer fields defined as boolean in openrtb.proto

### ISSUE THREAD

**Issue by sevebisogni** [google/openrtb#145]
Hi all, 

I'm trying to `Unmarshal` raw OpenRTB `json` `BidRequest`s and `BidResponse`s using golang's `jsonpb` using the openrtb.proto definition (https://github.com/google/openrtb/blob/master/openrtb-core/src/main/protobuf/openrtb.proto) as follows
```
br := new(openrtb.BidRequest)
jsonpbu := new(jsonpb.Unmarshaler)
jsonpbu.AllowUnknownFields = true
jsonpbu.Unmarshal(bytes.NewReader(<raw-json-byte-slice>), br)
```
yields
`json: cannot unmarshal number into Go value of type bool`

I've noticed the following fields are specified as type `integer` in the openRTB spec (https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf) and are defined as `bool` in your protobuf definition.

```
- BidRequest
    - test
    - source.fd
    - imp.instl
    - imp.clickbrowser
    - imp.secure
    - imp.banner.topframe
    - imp.banner.vcm
    - imp.video.skip
    - imp.video.boxingallowed
    - imp.audio.stitched
    - imp.pmp.private_auction
    - imp.native.aurlsupport
    - imp.native.durlsupport
    - imp.native.privacy
    - imp.native.assets[].required
    - site.privacypolicy
    - site.mobile
    - site.content.livestream
    - site.content.sourcerelationship
    - site.content.embeddable
    - app.privacypolicy
    - app.paid
    - app.content.livestream
    - app.content.sourcerelationship
    - app.content.embeddable
    - device.dnt
    - device.js
    - device.geofetch
    - device.lmt
    - regs.coppa
- BidResponse
    - seatbid.group
    - seatbid.bid.adm_native.assets[].required
```
Please note I'm unsure which OpenRTB version your proto is reflecting, but although a comment states `2.0` it contains fields which are in `2.5` but _not_ in `2.0`, so I linked `2.5`.

Can you offer any insight as to why this is the case? Is there a way I can get around this without modifying the generated `openrtb.pb.go` code? I'd like to use your definition without having to fork and maintain it, if possible.

Thanks very much!

**Comment by aravindbargurhiriyannaiah** [comment]
Hello @sevebisogni 
Can you please explain why this was closed? And how to get around the above discrepancies between the Proto files and IAB specification?

**Comment by opinali** [comment]
Hi, sorry for not noticing this way back before the issue was closed. The mapping of bool fields has been detailed elsewhere, but probably only in the openrtb discussion groups and other documents many years ago. But the TLDR is that this proto is biased for strong typing, this includes not only bools but also enums instead of ints everywhere like in the spec.

Some Protobuf libraries, including Google's public Protobuf project, have JSON serialization functionality that have an option to serialize bools to 1/0 and deserializing those back to bools. I am no specifically familiar with jsonpb but maybe there's an option like that too, by the way many JSON libraries in general support this option, for example in Jackson (the most popular JSON API for Java) you can do that with `@JsonFormat(shape = Shape.NUMBER)`. This is a very common issue in JSON because 1/0 take a lot less space than true/false, but using ints for fields that are semantically booleans is a very poor choice for any static-typed language.

The proto is perfectly compatible with the spec if you have a Proto/JSON library that can use the correct on-wire representation of 0/1. The spec only describes the on-wire messages, it doesn't describe an API.
