### ISSUE TITLE
How can I reject the bid request?

### ISSUE THREAD

**Issue by karenhovhannisian** [google/openrtb#63]
Hello everyone,

I am trying to integrate Smaato advertiser service(http://dspportal.smaato.com/), which uses OpenRTB standards. I want to reject the bid request which contains mime type which my ad doesn't support. For example bid request sends application/javascript (richmedia), but my ad supports only image/jpeg, image/png, image/gif. How can I reject such bid requests?

Thanks

**Comment by opinali** [comment]
Hi @karenhovhannisian, this library is only concerned with  the representation of OpenRTB messages, ideally you should checking this with Smaato's documentation or support. But since your question is about a pretty general feature of the protocol (so I don't think Smaato's implementation would do something unique): you need to check the `mimes` field of the request's `Banner`, `Video`, or `Image` assets for native impressions; in all cases the field is an array of all MIME types the request supports, so you can reject all impressions that don't include at least one of your image types in that list.
